version: "3"
services:
  analysis:
    image: joelnitta/moorea_filmies:1.0.0
    ports:
      - "8787:8787"
    volumes:
            - ".:/home/rstudio/moorea_filmies"
    environment:
      DISABLE_AUTH: "true"
    working_dir: /home/rstudio/moorea_filmies
