version: "3"
services:
  analysis:
    image: joelnitta/moorea_filmies:4.0.2
    ports:
      - "8787:8787"
    volumes:
            - "~:/home/rstudio/moorea_filmies"
    environment:
      DISABLE_AUTH: "true"
    working_dir: /home/rstudio/moorea_filmies
