version: "3"
services:
  analysis:
    image: rocker/verse:3.6.2
    ports:
      - "8787:8787"
    volumes:
      - ".:/home/rstudio/moorea_filmies"
    environment:
      DISABLE_AUTH: "true"
    working_dir: /home/rstudio/moorea_filmies
