# Load packages used in the analysis

library(conflicted)
library(targets)
library(tarchetypes)
library(ape)
library(assertr)
library(assertthat)
library(glue)
library(jntools)
library(janitor)
library(here)
library(lubridate)
library(patchwork)
library(scales)
library(ggtext)
library(kableExtra)
library(ggforce)
suppressPackageStartupMessages(library(ggtree))
suppressPackageStartupMessages(library(tidyverse))

conflict_prefer("col_factor", "readr")
conflict_prefer("filter", "dplyr")
conflict_prefer("rename", "dplyr")
conflict_prefer("gather", "tidyr")
