---
title: "Untitled"
output: html_document
bibliography: references.bib
editor_options: 
  markdown: 
    wrap: sentence
---

Intergenerational Niche Differentiation in Filmy Ferns (Hymenophyllaceae)^1^

Joel H. Nitta^2,5,6^, James E. Watkins, Jr.^3^, N. Michele Holbrook^2^, Ravahere Taputuarai^4^, Tristan W. Wang^2^, and Charles C. Davis^2^

Running Head: Intergenerational Niche Differentiation in Filmy Ferns

**PREMISE OF THE STUDY**: Desiccation tolerance was a key trait allowing plants to colonize land.
However, little is known about the transition from desiccation tolerant non-vascular plants to desiccation sensitive vascular ones.
Filmy ferns (Hymenophyllaceae) present a useful system to study how water-stress strategies differ between non-vascular and vascular stages within a single organism, as they have vascularized sporophytes and nonvascular gametophytes that are each capable of varying degrees of desiccation tolerance.

**METHODS**: We surveyed sporophytes and gametophytes of 22 species of filmy ferns on Moorea (French Polynesia).
We used chlorophyll fluorescence to measure desiccation tolerance and light responses.
We sequenced plastid *rbcL* and *trnHpsbA* to identify field-collected gametophytes, and conducted phylogenetically informed analyses to identify differences in physiology between life stages and growth habits.

**KEY RESULTS**: Gametophytes had similar or less desiccation tolerance and lower photosynthetic optima than sporophytes.
Despite their lack of greater physiological tolerances, gametophytes of several species occurred over a wider elevational range than conspecific sporophytes.
Epiphytes were more tolerant of desiccation than terrestrial species.

**CONCLUSIONS**: Our results show that filmy fern gametophytes and sporophytes differ in their physiology and niche requirements, and point to the importance of microhabitat in shaping the evolution of water-use strategies in vascular plants.

**KEYWORDS**: chlorophyll fluorescence; desiccation tolerance; DNA barcoding; filmy ferns; French Polynesia; gametophyte; Hymenophyllaceae; Moorea; photosynthesis

^1^Manuscript received \_\_\_\_ ; revision accepted \_\_\_\_.

^2^Department of Organismic and Evolutionary Biology and Harvard University Herbaria, Harvard University, Cambridge, Massachusetts 02138 USA;

^3^Department of Biology, Colgate University, 13 Oak Drive, Hamilton, New York 13346 USA; and

^4^Association Te Rau Ati Ati a Tau a Hiti Noa Tu, Mahina, Tahiti, French Polynesia

^5^Current address: Department of Botany, National Museum of Nature and Science, 4-1-1 Amakubo, Tsukuba, Ibaraki 305-0005 Japan

^6^Author for correspondence (email: joelnitta\@gmail.com)

The movement of plants from water to land was one of the most important evolutionary events in the history of the earth, fundamentally altering the global carbon and water cycle and setting the stage for modern terrestrial ecosystems [@Graham1993; @Kenrick1997a].
The transition from aquatic to terrestrial growth was complex, requiring the evolution of a suite of adaptations to survive in dry habitats bombarded with radiation [@Waters2003].
The earliest land plants were poikilohydric, i.e., they lacked any mechanisms to regulate water relations [@Raven1999].
Therefore, one particularly important early adaptation that enabled plants to survive on land was desiccation tolerance (DT), the ability to lose water until reaching equilibrium with atmospheric humidity, then recover upon rewetting [@Mishler1985].

Compared with the ubiquitous DT among the earliest land plants, the occurrence of DT varies across extant land plant lineages and life stages.
Many bryophytes have retained vegetative DT in the gametophyte stage [@Oliver2005, and references therein].
In extant vascular plants (tracheophytes), DT occurs in certain non-vegetative stages (e.g., seeds and pollen), but has largely been lost in vegetative tissues (with some notable exceptions, the so-called 'resurrection plants').
Instead, tracheophytes avoid desiccation with adaptations including a waxy cuticle, stomata, and an extensive vascular system.
Correlated with these differences in functional strategies to cope with water stress is a major difference in life cycle: in most tracheophytes (including all seed plants) the long-lived, dominant phase of the life cycle is the sporophyte (diploid phase), whereas in bryophytes it is the gametophyte (haploid phase).
Little is known about the details of the transition from desiccation tolerance to sensitivity, nor how this took place in conjunction with the switch from a gametophyte to a sporophyte-dominated life cycle; yet, these two steps underpin the radiation of plants onto dry land.

Ferns represent an important, understudied group of tracheophytes for investigating the transition from desiccation tolerance to desiccation avoidance in land plants.
Ferns are the only major lineage among land plants with sporophytes and gametophytes that are capable of growing independently from each other.
These two life stages differ drastically in their morphology and physiology---fern sporophytes have true vascular tissue and are homoiohydric (i.e., they regulate their internal water content), whereas fern gametophytes are much smaller (often *\<*1 cm), lack vascular tissue, and are poikilohydric.
Recent studies indicate that the gametophytes of many fern species are desiccation tolerant, while sporophytes of the same species are thought to lack DT [@WatkinsJr.2007c; @Pittermann2013a].
Thus, ferns present a unique opportunity to observe the transition from desiccation tolerance to desiccation avoidance across independently growing life phases within a single organism.

Filmy ferns (Hymenophyllaceae) represent a particularly interesting case for studying the ecological and evolutionary significance of vegetative DT across life stages in ferns.
Filmy ferns are a large family (ca. 430 spp.; PPG I, 2016) of primarily tropical, leptosporangiate ferns named for their remarkably thin leaf laminae, which are usually only a single cell layer in thickness and lack cuticle or stomata (Fig. 1A--D).
Filmy fern sporophytes are an exception to the 'typical' fern sporophyte described above because they have reverted to poikilohydry: their thin laminae allow for passive, rapid uptake and loss of moisture, thereby maintaining nearly constant equilibrium with atmospheric humidity (Raven, 1999).
Many species of epiphytic filmy ferns have extremely reduced root systems (Schneider, 2000), relying completely upon absorption through leaf laminae for water (Shreve, 1911), although terrestrial species possess true roots and use ground water (Dubuisson et al., 2011).
As would be expected from their poikilohydric nature, DT of varying degrees has been reported in sporophytes of many filmy fern species (see references below).

Filmy fern sporophytes encompass a broad diversity of growth forms (terrestrial, saxicolous, hemi-epiphytic, and holoepiphytic) and morphologies, with rhizome and leaf sizes varying over an order of magnitude (Hennequin et al., 2008; Nitta and Epps, 2009; Dubuisson et al., 2013).
Filmy fern gametophytes are similarly diverse, with morphotypes including filamentous, ribbon, and a combination of these two types (Fig. 1E--H).
While there are no quantitative data about DT in filmy fern gametophytes available, DT has been reported in gametophytes from several other fern lineages (Watkins et al., 2007; Watkins and Cardelús, 2012; Pittermann et al., 2013), and may be expected to occur in filmy ferns as well.
The possibility for varying degrees of vegetative DT in both stages of the life cycle of filmy ferns makes them a potentially useful system to compare how DT is utilized between haploid, non-vascular and diploid, vascular life stages.
Furthermore, the diversity of growth forms and habitats in filmy ferns makes them an ideal group for a comparative study of water-stress strategies (i.e., desiccation tolerance vs. desiccation avoidance) and the correlation of these strategies with ecological niche.

The degree of DT in filmy fern sporophytes occupying different niches has been relatively well studied.
In a series of elegant experiments on Jamaican filmy ferns, Shreve (1911) demonstrated that water-use strategies differ between species occupying contrasting habitats (i.e., terrestrial, low elevation epiphyte, and high elevation epiphyte).
Proctor (2003, 2012) investigated water relations and the ability to recover from desiccation in sporophytes of several filmy ferns, and found a general correlation between high DT and adaptation for high light levels in widespread species vs. low DT and adaptation to low light levels in species occupying more sheltered habitats.
In the only study to our knowledge including in situ physiological observations of hymenophyllaceous gametophytes, Johnson et al. (2000) found that gametophytes of *Vandenboschia speciosa* (Willd.) G.
Kunkel (= *Trichomanes speciosum* Willd.) are adapted for extremely low light environments, and operate at lower light levels than conspecific sporophytes.
Parra et al. (2009) and Saldan˜a et al. (2014) investigated the relationship between physiology (photosynthetic rates and water relations) and vertical stratification in several epiphytic filmy fern species (primarily genus *Hymenophyllum*) along tree trunks in Chile.
They found that species occurring at greater heights in the trees tended to have greater DT, higher photosynthetic capacity (A~max~), and lower rates of evapotranspiration.
A recent study using two species of *Hymenophyllum* demonstrated that DT in filmy ferns likely operates via a constitutive mechanism, which is more similar to that of bryophytes than other drought-tolerant vascular plants, thus allowing filmy ferns to adjust to dry conditions extremely rapidly (Cea et al., 2014).

Despite this considerable interest in filmy fern ecophysiology, with the sole exception of Johnson et al. (2000), no studies have compared physiology between gametophyte and sporophyte phases, and we are aware of none that have done so across multiple species.
Furthermore, to our knowledge, no physiological studies of filmy ferns have accounted for their phylogenetic relationships, and we lack an understanding of how physiological strategies have evolved in this clade.
In addition to DT, photosynthetic optima (adaptation to different light levels) are likely to be important in determining the niches of life stages and species of filmy ferns (Proctor, 2003; Parra et al., 2015; Flores-Bavestrello et al., 2016).
Terrestrial and epiphytic species experience different levels of photosynthetic radiation and desiccation, and light intensity varies with height along the host plant in epiphytes (Benzing, 1990; Watkins and Cardelús, 2009).
In a recent study (Testo et al., unpublished), the combined effect of desiccation and light stress was found to have a greater impact on filmy fern physiological performance than either of these stressors alone, suggesting the need to integrate studies of DT with photosynthesis to gain a full picture of physiological adaptation in filmy ferns.
Here, we leverage a recently developed DNA barcoding system (Nitta et al., 2016) to test several hypotheses related to DT and photosynthesis in a comparative phylogenetic framework including both filmy fern sporophytes and gametophytes: 1.) Epiphytic filmy ferns have higher DT and photosynthetic optima than non-epiphytic species.
2.) Amongst epiphytic filmy ferns, those occurring at high elevation have higher DT and photosynthetic optima than those at low elevation.
3.) For filmy ferns with gametophytes that occur over a wider range than sporophytes, the gametophyte has higher DT and photosynthetic optima than the sporophyte.

MATERIALS AND METHODS

***Study system***---We selected the island of Moorea, French Polynesia (17*◦*32' S, 149*◦*50' W) for our survey of filmy fern ecophysiology (Fig. 2).
Moorea is a small (135 km^2^; maximum elevation 1206 m) tropical oceanic island, located ca.
15 km NW of its larger sister island, Tahiti.
Despite its small size, it hosts a range of habitats including coastal strand, low elevation rainforest, and high elevation cloud forest.
At the time of the study, a total of 18 filmy fern species were known from Moorea (Murdock and Smith, 2003; Ranker et al., 2005; Nitta et al., 2011b; Florence, in press), including multiple terrestrial, saxicolous, and epiphytic species.
The two major clades of filmy ferns, the hymenophylloid and trichomanoid lineages (Pryer et al., 2001), are represented by similar numbers of species.
We follow the taxonomic system of Ebihara et al. (2006).

***Field survey***---We surveyed filmy ferns on Moorea as part of a larger study including all ferns of Moorea and Tahiti (Nitta et al., 2016).
During this study, 17 sampling sites were established from ca.
200 m to 1200 m primarily along trails to the summits of three large peaks on Moorea: Mt. Rotui (899 m), Mt. Mouaputa (880 m), and Mt. Tohiea (1206 m; Fig. 2).
At each site, sporophytes were sampled in a single 10 m *×* 10 m plot, and gametophytes sampled in two to three 50 cm *×* 50 cm subplots located within the sporophyte plot.
Epiphytes were sampled to a maximum height of ca.
2 m on their host plants.
Unlike many other fern species, filmy fern gametophytes have unique morphologies that allow them to be identified to family (e.g., filamentous, ribbon with round gemmae; Nayar and Kaur 1971).
This allowed us to specifically use field-collected filmy fern gametophytes for physiological tests, which we later identified to species using DNA barcoding (see below).
We characterized the elevational range of each species based on the results of the field survey; any species found with gametophytes occurring *\>*200 m above the maximum or below the minimum observed elevational range of sporophytes was considered 'widespread' (i.e., facultatively independent sensu Rumsey and Sheffield $$1996$$).
We scored growth habit of each species based on field observations as terrestrial, saxicolous, low elevation epiphyte (mostly occurring outside of cloud forest, i.e., below ca. 500 m), or high elevation epiphyte (mostly occurring in cloud forest, i.e., above ca. 500 m).

***Microclimate***---We characterized the microenvironment experienced by filmy ferns by logging relative humidity (RH) and temperature every 15 min from July 7, 2013 to July 5, 2014 at 16 of the sampling sites (Fig. 2).
To do this we used Hobo ProV2 dataloggers (Onset Computer Corporation, Bourne, Massachusetts, USA) with external sensors outfitted with radiation shields (RS1 or RS3, Onset Computer Corporation, Bourne, Massachusetts, USA) to prevent direct contact with precipitation and solar radiation.
To compare between terrestrial and epiphytic habitats, dataloggers were placed in pairs at each site (one 'epiphytic' datalogger at ca. 1.5 m on a tree, one 'terrestrial' datalogger at ca. 10 cm next to the tree).
During the study period, some dataloggers malfunctioned, presumably due to prolonged exposure to high humidity.
We excluded any days during which one or more dataloggers failed from the final dataset, and some sites are missing data completely for one or both dataloggers.
One terrestrial datalogger (Mt. Tohiea 393 m site) was lacking data for more than half of the survey period, but had data available for the same period from a preliminary survey conducted during the previous year (2012--2013).
We used the previous year's data for this site instead.
The final dataset included 201 days of data from 15 sites (26 dataloggers).
We tested for differences in climatic variables between epiphytic and terrestrial habitats using analysis of covariance (ANCOVA) with each climatic variable in turn as the response variable and elevation as the explanatory variable with habitat (terrestrial vs. epiphytic) as a cofactor.

***Desiccation tolerance***---Samples were collected in the field and stored in plastic bags with a small amount of water to keep them fresh during transport to the lab.
For sporophytes, 8--16 individuals (one individual = single whole frond including a ca. 2 cm section of rhizome) were used per treatment, and all individuals for each species came from a single population.
We did not attempt to differentiate genotypes between fronds in species with long-creeping rhizomes, which often form clonal mats; hence, in some cases, individuals may be genetically identical ramets.
All experiments were initiated within 48 h of collection.
Pre-treatment chlorophyll fluorescence (F~v~/F~m~) was measured in fresh plants after a 10 min period of dark-adaptation using a portable mini-PAM fluorometer (Walz Gmbh, Effeltrich, Germany).
Plants were then transferred to desiccation chambers containing saturated salts at three different desiccation intensities or a control treatment with moist tissues (100% RH), and water withheld for either a short (2 d) or long (15 d) interval (Testo and Watkins, 2013).
Conditions inside the desiccation chambers were monitored during the experiment using Hobo ProV2 dataloggers.
The desiccation chambers were kept in an air-conditioned room, and temperature inside the chambers ranged from 22--25 *◦*C.
Salts used for desiccation and their corresponding mean water potentials are as follows: LiCl (--282 MPa), Mg(NO~3~)~2~ (--86 MPa), and NaCl (--38 MPa).
Because field-collected gametophytes could not be identified to species prior to DNA extraction, no planned replication by species was possible; we therefore used the same treatment for all gametophytes (2 d at --86 MPa), and verified species of each individual after the experiment using the DNA barcode approach described below.
Thus, experiments involving gametophytes were sampled many times for some species whereas other species were not.
Following the desiccation treatment, plants were rewetted using water from a local stream.
Plants were allowed to rehydrate, and chlorophyll fluorescence was again measured at 0*.*5 h, 24 h, and 48 h following rewetting.
Ability to recover from desiccation was quantified by comparing pre- and post-treatment chlorophyll fluorescence yield (Watkins et al., 2007).

***Light responses***---Rapid light response curves were constructed for each species by measuring photosynthetic yield at gradually increasing levels of photosynthetically active actinic light (400--700 nm) with the Light Curve function of the mini-PAM portable chlorophyll fluorometer (Walz Gmbh, Effeltrich, Germany) as described by the manufacturer.
Briefly, the maximum yield (F~m~) was first measured in the absence of actinic light.
Next, plants were equilibrated to the actinic light for 30 s, and photosynthetic yield (∆F/F~m~) measured with a 0*.*8 s saturating pulse.
This was repeated for each photosynthetic photon flux density (PPFD) level, up to ca.
500 µmol·m^--2^ ·s^--1^.
Response curves were fitted using the equation *y* = *A*(1 --*e^-kx^*), where *y* is relative electron transport rate of photosystem II (RETR), *x* is PPFD, *A* is the asymptote of the curve, and *k* is a slope parameter; outliers at high PPFD likely to distort the curve were discarded (Proctor, 2012).
The PPFD at 95% saturation of RETR (PPFD~95%~) and maximum RETR (ETR~max~) were then calculated from the curve.
Light responses were measured in 8--16 field-collected sporophyte individuals for each species, and on single gametophyte individuals in the field, which were later identified to species using the DNA barcodes.

***DNA barcoding***---We used DNA barcoding to identify filmy fern gametophytes to species as described in Nitta et al. (2016).
Briefly, DNA extraction was performed using a modified CTAB protocol (Doyle and Doyle, 1987) or the Plant Mini DNEasy kit (Qiagen, Valencia, California, USA) following the manufacturer's protocol.
Chloroplast *rbcL* and *trnH--psbA* were amplified and sequenced using primers and protocols following Nitta et al. (2016).
For each marker, a reference library was constructed from sporophyte sequences using the makeblastDB command in BLAST (Altschul et al., 1997).
Field-collected gametophytes were identified by a local BLAST query against the reference library.
Gametophytes matching *\>*99.5% with a single reference sequence and no others were identified as that species; those that did not match any reference sequence or matched *\>*99.5% with multiple reference sequences were not identified and excluded from further analysis.

***Statistical analysis and phylogenetic comparative methods***---All statistical analyses were done in R v.3.2.1 (R Core Team, 2015).
Datasets and R scripts used in this study are available on Dryad (\#\#\#\#\#\#).

We derived the phylogenetic tree used in this study by extracting Hymenophyllaceae from the tree of Nitta et al. (2016) with the extract.clade function of the ape package in R (Paradis et al., 2004).
This tree is well-supported and generally in accord with previously published, more densely sampled phylogenies (Pryer et al., 2001; Dubuisson et al., 2003; Hennequin et al., 2006; Ebihara et al., 2007; Appendix S1, see Supplemental Data with the online version of this article).

We quantified the degree of phylogenetic signal in physiological traits using Blomberg's *K* (Blomberg et al., 2003) and Pagel's λ (Pagel, 1999; Freckleton et al., 2002) as implemented with the phylosig function in the phytools R package (Revell, 2012).
Both measures test the hypothesis that the trait of interest is evolving according to Brownian Motion (BM).
λ is a scaling parameter that ranges from zero to one: λ near zero indicates random distribution of trait values across the tree, and λ near one indicates evolution of traits along the phylogeny following BM.
For *K*, values near one indicate evolution of traits following BM; *K* *\>*1 indicates traits more conserved than expected under BM, and *K* *\<*1 indicates that traits have less phylogenetic signal than expected under BM.
We tested the significance of *K* by comparing the observed value against values from a null distribution of 1000 phylogenies with the traits randomly shuffled across the tips.
We tested the significance of λ with a log-likelihood test comparing the likelihood of the observed value of λ vs. λ = 0.
For all further analyses, we used methods that account for phylogenetic history for physiological traits that showed significant phylogenetic signal, and standard methods otherwise.

We used general linear mixed models (GLMMs) to investigate the effect of growth habit, range size, and life stage on DT (% recovery of F~v~/F~m~ after 48 h recovery from desiccation at --86 MPa for 2 d) and photosynthetic parameters (ETR~max~ and PPFD~95%~) using the MCMCglmm R package (Hadfield, 2010).
For each of the three response variables (DT, ETR~max~ , and PPFD~95%~), we used growth habit (epiphyte vs. non-epiphyte $$i.e., terrestrial or saxicolous$$) or range size (widespread vs. not widespread) and generation (sporophyte vs. gametophyte) and their interactions as fixed effects.
Two species were observed both as low-elevation epiphytes and saxicoles (Table 1), but we treated them as epiphytic to distinguish them from exclusively saxicolous species, which we regard as the more specialized growth habit.
We accounted for intraspecific variation and phylogeny (only for response variables with significant phylogenetic signal) by including species (within generation) and an inverse phylogenetic variance-covariance matrix as random effects, respectively (Hadfield, 2010).
We used an inverse-Gamma distribution for all priors, and ran analyses for 500 000 iterations, with burnin after 1000 iterations and thinning every 500 iterations.
Comparisons of DT, ETR~max~ , and PPFD~95%~ between gametophytes and sporophytes of the same species do not involve phylogeny, so we used a *t*-test for these.

To test for a correlation between environmental water potential and DT, we first derived a single minimum water potential value for each species by taking the average of the minimum daily water potential at all sites where that species was present.
We used minimum values because these may represent a climatic extreme that limits the occurrence of species.
We used data from the 'epiphytic' dataloggers mounted at 1*.*5 m on trees for epiphytic species and data from the 'terrestrial' dataloggers on the ground for non-epiphytic species.
Data from the Mt. Rotui 830 m site were excluded because this site is much more exposed than the other high elevation sites, and appears as a significant outlier in the microclimatic data (see Results).
This may be due to its location; unlike other mountains on Moorea, Mt. Rotui is completely isolated with no connecting ridges to other peaks (Fig. 2).
Since DT showed significant phylogenetic signal (see Results), we used phylogenetic generalized least squares (PGLS) to test for a relationship between environmental water potential and DT while taking phylogeny into account, using species' means.
We ran PGLS using the caper R package (Orme et al., 2013).

RESULTS

***Field survey***---Twenty-two filmy fern taxa (including one new record and two species that were recognized as multiple varieties) were observed as sporophytes, and 18 as gametophytes on Moorea in total (Table 1).
*Hymenophyllum braithwaitei* (Ebihara & K. Iwats.), only observed near the peak of Mt. Tohiea (1206 m), is a new record for Moorea and French Polynesia.
It was previously known only from Vanuatu and New Caledonia (Ebihara et al., 2010).
Three taxa with distinct *rbcL* sequences, morphology, and elevational ranges could be distinguished within the *Crepidomanes minutum* (Blume) K.
Iwats.
species complex, but species status of these taxa remains uncertain (Nitta et al., 2011a).
We refer to these here as *C. minutum* var.
1, 2, and 3.
Similarly, two members of the *Abrodictyum asae-grayi* (Bosch) Ebihara & K.
Iwats.
complex (also including *Abrodictyum caudatum* (Brack.) Ebihara & K.
Iwats.
in our tree; Appendix S1) were observed on the basis of *rbcL* and morphology, but as taxonomic treatment is beyond the scope of the current study we refer to them as *A. asae-grayi* var.
1 and 2.
In several species, gametophytes exceeded the maximum or minimum elevational range of sporophytes (Table 1) including *Callistopteris apiifolia* (C. Presl) Copel., *Crepidomanes minutum* var.
2 and 3, *Hymenophyllum digitatum* (Sw.) Fosberg, *Hymenophyllum javanicum* Spreng., *Hymenophyllum pallidum* (Blume) Ebihara & K.
Iwats., and *Polyphlebium borbonicum* (Bosch) Ebihara & Dubuisson.
All of these have sporophytes that are normally only found in cloud forest (ca. 500--1200 m), but gametophytes that are distributed to lower elevations.

***Microclimate***---Mean daily temperature was strongly correlated with elevation, and dropped ca.
6 *◦*C from the lowest surveyed site (201 m) to the highest (1206 m; Fig. 3).
Although epiphytic and terrestrial habitats were similar in temperature, epiphytic habitats tended to have lower daily mean RH, and greater daily variation in RH, than terrestrial ones (Fig. 3, Appendix S2).
This difference was greatest at low elevations, and smallest at high elevations.
One significant departure from these trends was observed at the Mt. Rotui 830 m site (indicated by arrows in Fig. 3).
This site is much more exposed than the other cloud forest sites (Fig. 2), and many of the plants on the N facing slope are stunted (J. Nitta, pers. obs.).
Daily variation in temperature and RH was much greater, and mean RH much lower, at this site than other high elevation sites.

***Phylogenetic signal***---Results of the tests for phylogenetic signal (Blomberg's *K* and Pagel's λ*)* were similar for sporophytes and gametophytes, revealing significant phylogenetic signal for DT (gametophytes *K* and λ both near 1, *P \<*0.05; sporophytes *K* = 0.78, *P* = 0.02 and λ = 0.96, *P* = 0.11), but no signal for PPFD~95%~ or ETR~max~ (Table 2).

***Desiccation tolerance***---Ability to recover from desiccation was tested in sporophytes of 15 species and gametophytes of 14 species, including 12 species with both life phases (Appendix S3).
A general correlation of DT with habitat was observed in sporophytes (Fig. 4).
Both terrestrial species (*Abrodictyum dentatum* (Bosch) Ebihara & K Iwats.
and *C. apiifolia*) lacked even moderate DT, and failed to recover from the gentlest treatment of 2 d at --38 MPa (more stringent tests were not conducted on these species after confirming their lack of DT at this level).
Saxicolous species (*Crepidomanes kurzii* (Bedd.) Tagawa & K.
Iwats., *Polyphlebium endlicherianum* (C. Presl) Ebihara & K.
Iwats., and *Vandenboschia maxima* (Blume) Copel.) also had low DT; only *C. kurzii* was able to recover from desiccation up to --86 MPa for 2 d but not more.
All epiphytic species were capable of recovering from desiccation to a certain degree, but ability varied between species.
Most low elevation epiphytes could not tolerate long periods (15 d) of desiccation; only *Crepidomanes bipunctatum* (Poir.) Copel.
was able to recover from desiccation longer than 2 d.
Most of the high elevation epiphytes could recover from 2 d treatments regardless of desiccation intensity (except for *H.* *pallidum* and *P.* *borbonicum*, which failed to recover from 2 d at --282 MPa), and many could withstand desiccation for 15 d.
Interestingly, *C. minutum* var.
2, *Hymenophyllum multifidum* (G. Forst.) Sw., and *Hymenophyllum polyanthos* (Sw.) Sw.
could recover from desiccation at --86 or --282 MPa for 15 d, but not --38 MPa.

Gametophytes of low elevation epiphytes had the highest DT (ca. 80% recovery), followed by high elevation epiphytes and saxicolous species (both with recovery from ca. 25% to 75%), with terrestrial species essentially non-tolerant (less than 20% recovery; Fig. 5).
DT of gametophytes did not significantly exceed that of sporophytes for any species except for saxicolous *P. endlicherianum* (Fig. 5; *t*-test, *P* = 0.012), and was significantly lower in gametophytes than sporophytes of some high elevation epiphytic species including *C. minutum* var.
2, *H.* *digitatum*, *H. polyanthos*, and *P. borbonicum* (Fig. 5; *t*-test, *P* = 0.0093, *\<*0.001, *\<*0.001, 0.012, respectively).

The GLMM showed that both generation and the interaction of generation and growth habit, but not growth habit alone, have a significant effect on DT while controlling for phylogeny (Table 3).
In contrast, range type (gametophytes widespread beyond sporophytes or not) has no significant effect on DT (Table 3).

***Photosynthetic optima***---Light responses were measured in sporophytes of 18 species and gametophytes of 11 species, including nine species with both life phases (Appendix S4).
Unlike DT, photosynthetic optima tended to vary between life phases, but not across growth habits or range type: sporophytes are adapted for higher light levels, whereas gametophytes are adapted for lower light levels (Fig. 5).
Sporophytes reached their maximum photosynthetic rate (PPFD~95%~) at light levels ca.
142 ± 46 µmol·m^--2^ ·s^--1^ , whereas gametophytes did so at 51 ± 22 µmol·m^--2^ ·s^--1^.
Similarly, sporophytes attained higher rates of electron transport (ETR~max~; 8.1 ± 2.7 µmol·m^--2^ ·s^--1^) than gametophytes (3.9 ± 0.9 µmol·m^--2^ ·s^--1^).
The GLMMs showed a significant effect of generation, but neither range type nor growth habit, on PPFD~95%~ and ETR~max~ (Table 3).

***Environmental water potential and DT***---Desiccation tolerance tended to increase with decreasing environmental water potential for both gametophytes and sporophytes (Fig. 6).
These trends were significant when analyzed using PGLS for sporophytes (*P* = 0.036) but not gametophytes (*P* = 0.123; Appendix S5).

DISCUSSION

Vegetative DT was a key innovation linked to the rise of early land plants, but is largely limited to non-vascular groups such as bryophytes and algae in modern plants.
Filmy ferns have received considerable attention over the years for their remarkable reversion to vegetative DT in the sporophyte phase (e.g., Shreve, 1911; Proctor, 2003; Cea et al., 2014).
Yet, no previous study to our knowledge has evaluated parallel physiology of sporophytes and gametophytes of filmy ferns in relation to DT.
Here, we present the first comparisons of physiological parameters between generations within filmy ferns in a phylogenetic comparative framework.

***Filmy fern sporophytes have a wide range of DT***---We found a wide variation of DT in filmy fern sporophytes on Moorea, from no tolerance in terrestrial species to tolerance of water potentials well below --200 MPa in some epiphytes.
Levels of similarly extreme DT have also been reported in other species of *Hymenophyllum* (Proctor, 2003, 2012) and a general correlation of habitat with DT in filmy ferns has been previously established (Shreve, 1911; Proctor, 2003, 2012; Parra et al., 2009; Saldan˜a et al., 2014; Testo et al., unpublished), but no other studies to our knowledge have documented a similar range of DT values in filmy ferns from a single site.
One may wonder then, what is the adaptive significance of being able to withstand drying at --200 MPa vs. --100 MPa when the ambient water potential is typically *\>*--5 MPa and only rarely, if ever, drops below −50 MPa.
The recent finding of a constitutive mechanism for DT in filmy ferns (Cea et al., 2014) supports the need for a relatively wide 'safety margin,' and similar (or even more extreme) levels of constitutive DT are well known in bryophytes (Oliver et al., 1993).
The conservative behavior of fern stomata, which lack a response to the plant stress hormone ABA, is well documented (Brodribb and McAdam, 2011; McAdam and Brodribb, 2012, 2013).
It is possible that filmy ferns also behave conservatively with respect to water-stress.
We suggest that the variation in DT observed here is relevant because it is correlated with habitat, and likely reflects overall physiological tolerance, not just artificial extremes.
For example, sporophytes of some high elevation epiphytes that we surveyed (*C. minutum* var. 2, *H. digitatum*, *H. multifidum*, *H. polyanthos*) seem to be able to better withstand intense vs. moderate desiccation, with higher recovery values at --282 and --86 MPa vs. --38 MPa when dry for 15 d.
This may be an adaptation to cloud forest conditions; although cloud forests are frequently moist due to constant fog, dry periods are intense during the times when there is no cloud cover.
The complete lack of DT in terrestrial species is not surprising, considering they have much more direct access to water than epiphytes and therefore substantially less selective pressure to maintain DT.
Since controls kept at 100% RH maintained F~v~/F~m~ values near pre-treatment levels in all sporophytes (Appendix S3), it is unlikely that the lack of tolerance seen in terrestrial species is due solely to removal from the soil.
Comparison of DT with the minimum water potential envelope of each species (Fig. 6) indicates that sporophytes of non-tolerant terrestrial and saxicolous species may not be able to occur in habitats with minimum water potential exceeding ca.
--7 MPa.
In contrast, habitats with minimum water potential below --7 MPa are nearly all epiphytic, and the filmy fern sporophytes occurring there are all capable of DT.

***Filmy fern gametophytes are not more stress-tolerant than sporophytes***---Contrary to our hypotheses, gametophytes of filmy ferns are in general not more tolerant of the abiotic environment (light levels and water potential) than sporophytes.
This differs from other fern groups with desiccation tolerant gametophytes but desiccation sensitive sporophytes (Watkins et al., 2007).
In the filmy ferns we studied, DT levels of both sporophytes and gametophytes largely reflected habitat; in general, epiphytic species tended to have higher DT than terrestrial or saxicolous species, regardless of life stage.
Interestingly, this echoes much earlier field observations (not experimental data) by Holloway (1930) on filmy fern gametophytes in New Zealand: he reported apparent DT in gametophytes of *Hymenophyllum rarum* R.
Br.
and *H. villosum* Colenso, both high elevation epiphytes with desiccation tolerant sporophytes, and lack of DT in terrestrial filamentous gametophytes of *Polyphlebium colensoi* (Hook.) Ebihara & K.
Iwats., *Abrodictyum strictum* (Menzies ex Hook. & Grev.) Ebihara & K.
Iwats., and *A. elongatum* (A. Cunn.) Ebihara & K.
Iwats.
occupying moist, protected sites on the forest floor.
Watkins et al. (2007) also found that DT of fern gametophytes tended to match habitat, with terrestrial species having lower DT than epiphytes.
However, we found that within high elevation epiphytes, gametophytes had lower DT than sporophytes, and only one species (saxicolous *P. endlicherianum*) with gametophytes that had significantly greater DT than sporophytes (Fig. 5).
At high elevation sites (i.e., cloud forest), epiphytic ferns often occur in a dense matrix of bryophytes (Fig. 1B).
It is possible that this bryophyte cover helps to retain moisture during brief periods of drought and thus protect the epiphytic fern gametophytes that grow amongst them.
More detailed studies of the high elevation epiphytic environment and interactions between co-occurring gametophytes of ferns and bryophytes are needed to test this hypothesis.

Although we predicted that species with gametophytes that occur beyond the range of their sporophytes would have higher DT and be adapted for higher light levels, this was not the case.
This is perhaps best illustrated by *C. apiifolia* (Fig. 1D, E, H).
Sporophytes of this species are usually restricted to moist cloud forest sites from ca.
600--1200 m, but we observed gametophytes over a much wider range, down to 200 m.
A similar distribution pattern has been reported in congeneric *Callistopteris baldwinii* (D. C. Eaton) Copel.
from Hawaii (Dassler and Farrar, 1997).
Since gametophytes of *C. apiifolia* are common on Moorea and have a unique morphology (Nitta et al., 2016), we were able to collect enough material of this species for additional tests of DT at higher humidity levels (48 h at 75% and 100% RH; results not shown).
However, it still failed to recover from even these gentle treatments.
This suggests that the widespread gametophytes of *C. apiifolia* do not rely on DT to attain their distribution, but instead must do so via some other mechanism.
Although we measured terrestrial microhabitats by positioning sensors a few cm above the ground, these sensors are still outside of the boundary layer.
It is likely that the gametophytes of *C. apiifolia* do not actually experience the conditions measured with our 'terrestrial' dataloggers, but instead grow within a much more consistently moist boundary layer.
Gametophytes of *C. apiifolia* produce gemmae (Fig. 1E, H), and often form dense clonal mats.
In the case that their microhabitats do become too dry, they may suffer loss at the edge of the population, then recover by clonal growth (Farrar et al., 2008).
Furthermore, the complex surface of clonal mats has been shown to increase the boundary layer and decrease evaporation rates in mosses (Rice et al., 2001), and may function similarly in *C. apiifolia*.
Other filmy fern species also produce gemmae, but they are much more frequent in *C. apiifolia*, and the large size of the clonal mats formed by *C. apiifolia* indicate that it may have a high growth rate (J. Nitta, pers. obs.).
It is possible that there is a tradeoff between growth rate and DT, such that species capable of rapid asexual growth like *C. apiifolia* are unable to tolerate desiccation, but slower growing epiphytes such as *Hymenophyllum* spp.
can better tolerate it (Oliver et al., 2000).
Growth rates of tolerant and non-tolerant gametophytes including quantification of gemmae production should be investigated in these species to test this hypothesis.

***Gametophytes are adapted for lower light levels than sporophytes***---Unlike DT, photosynthetic parameters did not vary significantly between species from different habitats.
Rather, we observed a clear intergenerational difference, with gametophytes consistently adapted for lower light levels than sporophytes (Fig. 5, Table 3).
In the only other study to our knowledge that compared photosynthetic rates between gametophytes and sporophytes of a filmy fern, Johnson et al. (2000) also found that gametophytes of *V. speciosa* reached maximum ETR at lower levels than sporophytes: in gametophytes of this species, photosynthesis became saturated at a PPFD of 4--5 µmol·m^--2^ ·s^--1^ in the field or 30--50 µmol·m^--2^·s^--1^ in the lab vs. 30--50 µmol·m^--2^ ·s^--1^ for the sporophyte (lab measurement only).
Although we found similar differences in direction between gametophytes and sporophytes, the measurements of Johnson et al. (2000) are considerably lower than what we observed in the field for both Moorean filmy fern gametophytes (PPFD~95%~ ca. 40--60 µmol·m^--2^ ·s^--1^) and sporophytes (PPFD~95%~ ca. 130--160 µmol·m^--2^ ·s^--1^).
This makes sense in light of the fact that *V. speciosa* is an extremely deep-shade plant, with gametophytes occupying protected rock crevices that receive less than 1 µmol·m^--2^·s^--1^ PPFD for most of the day (Johnson et al., 2000); many of the gametophytes sampled in our study occur in more exposed conditions.
It is surprising, however, that we did not observe any differences between species in different habitats, given that light levels should vary between tree trunks and the forest floor, at least on a ca.
1 m scale.
It is possible that the actual light levels experienced by gametophytes growing in these habitats may not vary significantly if they occupy protected microsites such as bryophyte mats or crevices in rock or bark.

***Influence of phylogeny on traits***---Previous studies of filmy fern ecophysiology also found a link between habitat and DT and/or photosynthetic rates (Proctor, 2003, 2012; Parra et al., 2009; Saldan˜a et al., 2014); however, ours is the first to our knowledge to investigate this pattern while taking phylogeny into account.
We detected significant phylogenetic signal in DT, suggesting that phylogeny should be considered when interpreting differences in DT between species (Table 2).
In contrast, the lack of phylogenetic signal in photosynthetic traits, coupled with the clear intergenerational differences we observed, suggest that sporophytes and gametophytes are adapted for different light levels regardless of clade or ecological niche.
In a more densely sampled study of morphological evolution in the trichomanoid clade, Dubuisson et al. (2013) identified several morphological changes including reduced stele and root systems associated with the evolution of epiphytic growth within the HE subclade (comprising the genera *Polyphlebium*, *Didymoglossum*, *Crepidomanes*, and *Vandenboschia*).
It is possible that both reduced morphology and increased DT are parts of an integrated adaptive strategy for epiphytic growth within this subclade of filmy ferns, and have evolved together repeatedly.
However, Dubuisson et al. (2013) were unable to determine if these morphological changes had occurred independently, or if there was a single origin at the base of the HE clade followed by multiple losses.
Increased sampling of both morphological and physiological traits of additional trichomanoid taxa is needed to distinguish between these scenarios.

***Concluding remarks and future directions***---In filmy ferns, both sporophyte and gametophyte generations are poikilohydric; however, we have found here that this does not mean they necessarily share similar physiological optima.
Although filmy fern sporophytes are often of small stature, elevating a leaf even a few cm above the substrate surface means escape from the boundary layer and exposure to substantially greater evapotranspiration.
It is likely that even in this clade, wherein the physiological divide between sporophyte and gametophyte is probably the smallest amongst ferns, the two generations experience substantially different selective pressures.
Fossils indicate that some of the earliest vascular plants may have had sporophytes and gametophytes that were both branched and small (Kenrick and Crane, 1997), but it is unclear at what point selective pressures began to diverge to favor large, complex sporophytes and small, simple gametophytes.
The relevance of plant size to water relations is supported by a recent study showing increased DT in smaller size classes of the epiphytic fern *Asplenium auritum* Sw.
(Testo and Watkins, 2012).
Future studies of DT in filmy ferns should include juvenile stages of the sporophyte, which are expected to experience similar microhabitats as gametophytes, to better determine the role of microhabitat vs. life stage (and plant size) on DT.
Finally, more detailed analyses of the strategies used by each generation to cope with desiccation stress, such as transcriptomics, are needed to better understand the ecology and evolution of filmy ferns as well as the transition from desiccation tolerance to avoidance in vascular plants.

ACKNOWLEDGEMENTS

Members of the Davis Lab and Jonathan B. Losos provided helpful discussion and comments on drafts.
Saad Amer, Tohei Theophilus, and Suzanne Vinnette assisted with fieldwork and experiments.
Evan Zeng helped with analysis of microclimatic data.
Weston Testo provided advice on settings for the DT test.
Staff at the University of California Berkeley's Richard B. Gump South Pacific Research Station, Moorea, French Polynesia, in particular Valentine Brotherson, Neil Davies, Hinano Teavai-Murphy, and Frank Murphy, provided logistical support for fieldwork.
Funding provided in part by the National Science Foundation (Doctoral Dissertation Improvement Grant DEB-1311169 to JHN and CCD), Setup Funds from Harvard University to CCD, American Society of Plant Taxonomists (Research Grant for Graduate Students to JHN), Garden Club of America (Award in Tropical Botany to JHN), Harvard University Herbaria (Fernald Fieldwork Fellowship to JHN), Society of Systematic Biologists (Graduate Student Research Award to JHN), and Systematics Association (Systematics Research Fund to JHN).
